Algoritmo "Area do Losango"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson
// Descrição: Leia os valores da diagonal maior e da diagonal
// menor de um losango e calcule sua área.
// Autor(a): Lariisa
// Data atual: 18/04/2026
Var
// Seção de Declarações das variáveis
diagonal1, diagonal2, area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite o diagonal maior do losango")
leia (diagonal1)
escreval ("Digite o diagonal menor do losango")
leia (diagonal2)
area <- (diagonal1 * diagonal2) / 2
escreval ("A área do losango é: ", area)




Fimalgoritmo