Algoritmo "Area do Paralelogramo"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson
// Descrição: Leia a base e a altura de um paralelogramo e calcule sua área.
// Autor(a): Larissa
// Data atual: 18/04/2026
Var
// Seção de Declarações das variáveis
base, altura, area: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite a base do Paralelogramo")
leia (base)
escreval ("Digite a altura do Paralelogramo")
leia (altura)
area <- altura*base
escreval ("A área do Paralelogramo é: ", area)

Fimalgoritmo