Algoritmo "Comprimento da Circunferencia"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson
// Descrição: Leia o raio de um círculo e calcule o comprimento
// da circunferência.
// Autor(a): Larissa
// Data atual: 18/04/2026
Var
// Seção de Declarações das variáveis
raio, comprimento, p: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite o raio do círculo")
leia (raio)
p<- 3,14
comprimento<- 2*p*raio
escreval("o comprimento do círculo é: ", comprimento)


Fimalgoritmo