Algoritmo "Conversao de Metros para Centimetros"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson
// Descrição: Leia um valor em metros e converta para centímetros.
// Autor(a): Larissa
// Data atual: 18/04/2026
Var
// Seção de Declarações das variáveis
cm, metros: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite quantos metros você ira converter para centimetros")
leia(metros)
cm <- metros * 100
escreval ("Você tem: ",cm, "cm")

Fimalgoritmo