Algoritmo "Conversão de Temperatura"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson
// Descrição: Leia uma temperatura em graus Celsius e converta
// para Fahrenheit.
// Autor(a): Larissa
// Data atual: 18/04/2026
Var
// Seção de Declarações das variáveis
temperatura, convertido: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite a temperatura que você quer converter")
leia(temperatura)

convertido<- (temperatura * 9/5) + 32
escreval ("A temperatura convertida para Fahrenheit é ", convertido)



Fimalgoritmo