Algoritmo "Idade em Meses e Dias"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson
// Descrição: Leia a idade de uma pessoa em anos e calcule a
// idade aproximada em meses e dias.
// Autor(a): Larissa
// Data atual: 18/04/2026
Var
// Seção de Declarações das variáveis
idade, meses, dias: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite a sua idade")
leia (idade)
meses<- idade * 12
dias <- idade * 365
escreval ("Você tem ", meses, " em meses vividos")
escreval ("Você tem ", dias, " em dias vividos")


Fimalgoritmo