Algoritmo "Media de Tres Valores"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson
// Descrição: Leia três números e calcule a média aritmética.
// Autor(a): Larissa
// Data atual: 18/04/2026
Var
// Seção de Declarações das variáveis
valor1, valor2, valor3, media: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite o primeiro valor: ")
leia(valor1)
escreval ("Digite o segundo valor: ")
leia(valor2)
escreval ("Digite o terceiro valor: ")
leia(valor3)
media <- (valor1+valor2+valor3) / 3
escreval ("A média é: ", media)

Fimalgoritmo