Algoritmo "Perimetro de um Retangulo"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson
// Descrição: Leia o valor do lado de um retangulo e calcule o perímetro.
// Autor(a): Larissa
// Data atual: 18/04/2026
Var
// Seção de Declarações das variáveis
largura, altura, perimetro: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite a largura do retângulo: ")
leia(largura)
escreval ("Digite a altura do retângulo: ")
leia(altura)

perimetro<- (largura + altura) * 2
escreval ("O perimetro do retângulo é ", perimetro)

Fimalgoritmo