Algoritmo "Perímetro do Retângulo"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson
// Descrição: Leia a base e a altura de um retângulo e calcule
// seu perímetro.
// Autor(a): Larissa
// Data atual: 18/04/2026
Var
// Seção de Declarações das variáveis
lado1, lado2, lado3, lado4, perimetro: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite o primeiro lado do retangulo")
leia(lado1)
escreval ("Digite o segundo lado do retangulo")
leia(lado2)
escreval ("Digite o terceiro lado do retangulo")
leia(lado3)
escreval ("Digite o quarto lado do retangulo")
leia(lado4)
perimetro <- lado1+lado2+lado3+lado4
escreval ("O perimetro do retângulo é: ", perimetro)


Fimalgoritmo