Algoritmo "Perímetro do Quadrado"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson
// Descrição: Leia o valor do lado de um quadrado e calcule o perímetro.
// Autor(a): Larissa
// Data atual: 18/04/2026
// Seção de Declarações das variáveis
var
lado1, lado2,lado3, lado4,  perimetro: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite o primeiro lado do quadrado")
leia (lado1)
escreval ("Digite o segundo lado do quadrado")
leia (lado2)
escreval ("Digite o terceiro lado do quadrado")
leia (lado3)
escreval ("Digite o quarto lado do quadrado")
leia (lado4)
perimetro <- lado1+lado2+lado3+lado4
escreval ("O perimetro do quadrado é: ", perimetro)



Fimalgoritmo