Algoritmo "Troca de Valores"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson
// Descrição: Leia dois valores armazenados nas variáveis A e B.
// Troque os valores entre elas.
// Autor(a): Larissa
// Data atual: 18/04/2026
Var
// Seção de Declarações das variáveis
valor1, valor2: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite o valor do A: ")
leia(valor1)
escreval ("Digite o valor do B: ")
leia(valor2)

escreval("O valor de A é: ", valor2)
escreval("O valor de B é: ", valor1)



Fimalgoritmo