Algoritmo "Valor da Compra"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson
// Descrição: Leia o preço de um produto e a quantidade comprada.
// Calcule o valor total da compra.
// Autor(a): Larissa
// Data atual: 18/04/2026
Var
// Seção de Declarações das variáveis
valor, total, quantidade: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite o quantidade de produtos que você comprou:")
leia(quantidade)
escreval ("Digite o valor do produtos que você comprou:")
leia(valor)
total <- quantidade * valor
escreval ("O total da sua compra foi de:", total)



Fimalgoritmo