Algoritmo "Área do Retângulo"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson
// Descrição: Leia a base e a altura de um retângulo e calcule sua área.
// Autor(a): Larissa
// Data atual: 18/04/2026
Var
// Seção de Declarações das variáveis
base, altura, area: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite a base do retangulo")
leia(base)
escreval ("Digite a altura do retangulo")
leia(altura)
area <- base * altura
escreval ("A área do retangulo é: ", area)



Fimalgoritmo