Algoritmo "Área do Triangulo"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson
// Descrição: Leia a base e a altura de um triângulo e calcule
// sua área.
// Autor(a): Larissa
// Data atual: 18/04/2026
Var
// Seção de Declarações das variáveis
base, altura, area:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite a base do triângulo:")
leia(base)
escreval ("Digite a altura do triângulo:")
leia(altura)
area <- (base*altura) / 2
escreval ("A área do triângulo é: ", area)



Fimalgoritmo