Algoritmo "Área do Círculo "
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson
// Descrição: Leia o valor do raio de um círculo e calcule sua área.
// Autor(a): Larissa
// Data atual: 18/04/2026
Var
// Seção de Declarações das variáveis
p: real
raio, area: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite o raio do circulo")
leia(raio)
p<- 3,14
area<- (raio * raio) * p
escreval ("o valor da area do circulo é: ", area)

Fimalgoritmo